name: Pages

on:
  push:
    branches: [master]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22
        uses: actions/setup-node@v1
        with:
          node-version: "22"
      - run: npm install
      - name: Create Pages
        run: npm run typedoc
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
